### MUST CHANGE ###
wxxeibo:
  short_name: ann-dau
  long_name: Ann Dau
  long_name2: Ann Dâu
  main_photo: https://raw.githubusercontent.com/ann-dau/photos/master/12653751255_7fbc632f2a.jpg
### MUST CHANGE ###

github:
  url: "http://localhost:4000"
photos_repo:
  url: "https://ann-dau.github.io/attachments"
assets:
  cache: false
